# Generated by Django 5.2.7 on 2025-11-01 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('RESET', 'Password Reset'), ('VERIFY', 'Account Verification')], default='RESET', max_length=10),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BS_CS', 'B.S. Computer Science'), ('BS_IT', 'B.S. Information Technology'), ('MS_CS', 'M.S. Computer Science'), ('MBA', 'MBA')], max_length=32)),
                ('catalog_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('code', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('credits', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
            ],
            options={
                'ordering': ['program', 'catalog_year', 'code'],
                'unique_together': {('program', 'catalog_year', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BS_CS', 'B.S. Computer Science'), ('BS_IT', 'B.S. Information Technology'), ('MS_CS', 'M.S. Computer Science'), ('MBA', 'MBA')], max_length=32)),
                ('catalog_year', models.PositiveSmallIntegerField(help_text='e.g., 2024', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('term', models.CharField(blank=True, max_length=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='users.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_classes', to='users.studentprofile')),
            ],
            options={
                'unique_together': {('profile', 'course')},
            },
        ),
    ]
