# Generated by Django 5.2.7 on 2025-11-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_emailotp_purpose_course_studentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='completed_codes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
