# Generated by Django 5.2.7 on 2025-11-02 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_completed_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='users.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avg_credits_per_term',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='max_credits_next_term',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=4),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('season', models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall')], max_length=2)),
            ],
            options={
                'ordering': ['year', 'season'],
                'unique_together': {('year', 'season')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='offered_in',
            field=models.ManyToManyField(blank=True, related_name='offerings', to='users.term'),
        ),
        migrations.CreateModel(
            name='ProgramRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BS_CS', 'B.S. Computer Science'), ('BS_IT', 'B.S. Information Technology'), ('MS_CS', 'M.S. Computer Science'), ('MBA', 'MBA')], max_length=32)),
                ('catalog_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('required_credits', models.PositiveIntegerField(default=120)),
                ('courses', models.ManyToManyField(blank=True, to='users.course')),
            ],
            options={
                'unique_together': {('program', 'catalog_year')},
            },
        ),
    ]
