# Generated by Django 5.2.7 on 2025-11-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereq_mode',
            field=models.CharField(choices=[('ALL', 'All listed are required'), ('ANY', 'Any one is sufficient')], default='ALL', help_text="If 'ANY', completing any one of the listed prerequisites is enough.", max_length=3),
        ),
    ]
