# Generated by Django 5.2.7 on 2025-11-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course_prereq_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereq_note',
            field=models.TextField(blank=True, default='', help_text='Optional note you type when adding/editing this course (shown above prerequisites in Admin).'),
        ),
    ]
