# Generated by Django 5.2.7 on 2025-11-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_course_prereq_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prereq_note',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional short description of this course.'),
        ),
    ]
