# Generated by Django 5.2.7 on 2025-11-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_course_prereq_note_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Course number, e.g., UPPER', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section code, e.g., A1, B2', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Department prefix, e.g., Asian American Studies, Communication Studies', max_length=16),
        ),
    ]
