# Generated by Django 5.2.7 on 2025-11-16 23:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_course_level_course_section_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Course number, e.g., 151', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Section code, e.g., 01 or A', max_length=16),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Department prefix, e.g., CS, AAS', max_length=32),
        ),
        migrations.CreateModel(
            name='PrerequisiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optional label, e.g., 'Math alternatives'", max_length=64)),
                ('min_required', models.PositiveSmallIntegerField(default=1, help_text='How many from this group are required.', validators=[django.core.validators.MinValueValidator(1)])),
                ('for_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_groups', to='users.course')),
                ('options', models.ManyToManyField(blank=True, help_text='Courses that can satisfy this group.', related_name='as_prereq_option', to='users.course')),
            ],
        ),
    ]
