# Generated by Django 5.2.7 on 2025-11-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tag_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, help_text='Course number, e.g., LOWER', null=True),
        ),
    ]
