# Generated by Django 4.2.27 on 2025-12-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, help_text='Course number, e.g., LOWER', max_length=50, null=True),
        ),
    ]
