# Generated by Django 4.2.27 on 2025-12-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedclass',
            name='grade',
        ),
    ]
