# Generated by Django 4.2.27 on 2025-12-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_completedclass_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='corequisites',
            field=models.ManyToManyField(blank=True, related_name='as_corequisite_for', to='users.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='as_prerequisite_for', to='users.course'),
        ),
    ]
