# Generated by Django 4.2.27 on 2026-01-16 06:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_course_corequisites_alter_course_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programrequirement',
            name='courses',
        ),
        migrations.CreateModel(
            name='ProgramRequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Humanities, Math Core, Electives', max_length=80)),
                ('min_required', models.PositiveSmallIntegerField(default=1, help_text='How many courses must be completed from this group', validators=[django.core.validators.MinValueValidator(1)])),
                ('courses', models.ManyToManyField(blank=True, help_text='Courses that belong to this requirement group', to='users.course')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.programrequirement')),
            ],
        ),
    ]
