# Generated by Django 4.2.27 on 2026-02-11 06:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_remove_programrequirement_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereq_mode',
            field=models.CharField(choices=[('ALL', 'All listed are required'), ('ANY', 'Any one is sufficient')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='prerequisitegroup',
            name='min_required',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prerequisitegroup',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='prerequisitegroup',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='as_prereq_option', to='users.course'),
        ),
        migrations.AlterField(
            model_name='programrequirementgroup',
            name='courses',
            field=models.ManyToManyField(blank=True, to='users.course'),
        ),
        migrations.AlterField(
            model_name='programrequirementgroup',
            name='min_required',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='programrequirementgroup',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='DPRUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=users.models.dpr_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpr_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
