# Generated by Django 4.2.27 on 2026-02-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_course_description_alter_course_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InProgressClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_progress', to='users.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_progress_classes', to='users.studentprofile')),
            ],
            options={
                'unique_together': {('profile', 'course')},
            },
        ),
    ]
