# Generated by Django 4.2.27 on 2026-03-29 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_inprogressclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('min_required', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_double_count', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='requirement_blocks', to='users.course')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='users.programrequirement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PathRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('paths', models.JSONField(blank=True, default=list)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_rules', to='users.programrequirement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
