# Generated by Django 4.2.29 on 2026-04-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_requirementblock_pathrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementblock',
            name='count_group',
            field=models.CharField(blank=True, default='group4', help_text='Use group1, group2, group3, or group4 for counting rules.', max_length=20),
        ),
    ]
