# Generated by Django 4.2.29 on 2026-04-08 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_requirementblock_count_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_plans', to='users.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_plans', to='users.term')),
            ],
            options={
                'ordering': ['position', 'term__year', 'term__season'],
                'unique_together': {('profile', 'term')},
            },
        ),
        migrations.CreateModel(
            name='PlannedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('planned', 'Planned')], default='planned', max_length=16)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_courses', to='users.course')),
                ('term_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_courses', to='users.termplan')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('term_plan', 'course')},
            },
        ),
    ]
